spring.application.name=greeting
logging.file.name=logs/mylog.log
spring.web.resources.static-locations=file:src/main/resources/static

#DB URL
spring.datasource.url=jdbc:mysql://localhost:3306/greeting_2026_db
#identifiers useed for auth on MySQL
spring.datasource.username=user
spring.datasource.password=user

spring.jpa.generate-ddl=true
#(create, create-drop,validate,update)
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
